import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  phoenix: [{ type: 'autogenerated', dirName: 'Phoenix' }],
  bolt: [{ type: 'autogenerated', dirName: 'Bolt' }],
  carbon: [{ type: 'autogenerated', dirName: 'Carbon' }],
  zephyr: [{ type: 'autogenerated', dirName: 'Zephyr' }],
  // boltWebAddon: [{ type: 'autogenerated', dirName: 'BoltWebAddon' }],
};

export default sidebars;