import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  phoenix: [{ type: 'autogenerated', dirName: 'Phoenix' }],
  bolt: [{ type: 'autogenerated', dirName: 'Bolt' }],
  carbon: [{ type: 'autogenerated', dirName: 'Carbon' }],
  zephyr: [{ type: 'autogenerated', dirName: 'Zephyr' }],
  prism: [
    {
      type: 'category',
      label: 'Start here',
      collapsed: false,
      items: ['Prism/Prism', 'Prism/introduction', 'Prism/installation', 'Prism/features'],
    },
    {
      type: 'category',
      label: 'Server configuration',
      items: [
        'Prism/commands-and-permissions', 'Prism/permissions', 'Prism/bot-configuration',
        'Prism/database', 'Prism/messages', 'Prism/placeholders',
      ],
    },
    {
      type: 'category',
      label: 'Combat styles',
      items: [
        'Prism/crystal-bot', 'Prism/mace-bot', 'Prism/spearmace-bot', 'Prism/sword-bot',
        'Prism/netherite-pot-bot', 'Prism/cart-bot-mechanics', 'Prism/diamond-smp-combat',
        'Prism/uhc-bot',
      ],
    },
    {
      type: 'category',
      label: 'Developer integrations',
      items: ['Prism/api', 'Prism/api-examples', 'Prism/arenas'],
    },
  ],
  // boltWebAddon: [{ type: 'autogenerated', dirName: 'BoltWebAddon' }],
};

export default sidebars;
