# This is the main configuration file for Bolt.
# As you can see, there's tons to configure. Some options may impact gameplay, so use
# with caution, and make sure you know what each option does before configuring.
# If you need help with the configuration or have any questions related to Bolt,
# join us in our Discord

# DO NOT TOUCH!
SYSTEM:
  CONFIG-VERSION: 1
GENERAL:
  
  # This is where players will teleport on join and after a match
  SPAWN-LOCATION: ""
  
  # Will players get teleported to the spawn location when they join
  SPAWN-ON-JOIN: true
  
  # The radius of the spawning circle in FFA matches/events
  FFA-SPAWN-RADIUS: 10
  
  # You can set the default party members size limit here
  DEFAULT-PARTY-LIMIT: 15
  
  # This world is where arenas all arenas will be pasted according to grid
  ARENA-WORLD: "world"
  
  # Do NOT touch this, unless you know what you are doing!
  ARENA-GRID-SPACING-X: 1000
  
  # Do NOT touch this, unless you know what you are doing!
  ARENA-GRID-SPACING-Z: 1000
  
  # Do NOT touch this, unless you know what you are doing!
  ARENA-GRID-Y-LEVEL: 80
  
  # Toggling this on will make arena resetting use FAWE and blocks that were tracked to reset.
  # While, default system is taking a copy of the arena's each chunk's sections and restoring them for reset.
  # The default system is memory intensive but is very fast and has minimal lag. This system is recommended for memory capped servers.
  MEMORY-OPTIMIZED-ARENA-RESET: true
  
  # Only change this if you are going to reset stats or don't have any.
  STARTING-ELO: 1000
  
  # Should we distribute experience to players in the match?
  # Disabling this will render experience un-attainable and useless.
  # Which would essentially make it same as before experience was added.
  DISTRIBUTE-EXPERIENCE: true
  
  # Prevents donators from flying too far out from spawn or spectators from arena.
  PREVENT-FLY-OUT-OF-BOUNDS: true
  
  # This option preloads all arena chunks. This is automatically done if 'MEMORY-OPTIMIZED-ARENA-RESET' is off.
  PRE-LOAD-CHUNKS: false
  
  # This option prevents chunks from unloading inside arenas that are being used.
  DONT-UNLOAD-CHUNKS: false
  
  # Turn this off if you have a cracked server, because its useless.
  CHECK-MOJANG-FOR-LEADERBOARD-NAMES: false
  
  # If enabled, players in lobby can shift-right click a player to duel them.
  SHIFT-CLICK-DUEL: true
  
  # Should we hide players that aren't in your party?
  HIDE-OTHER-PLAYERS: false
  
  # Should we enable help command?
  HELP-COMMAND: true
  
  # Should we disable the '/bolt reset' command that wipes mongo?
  DISABLE-RESET-COMMAND: true
  
  # Here you can change the duel request sound, the default is NOTE_PLING
  DUEL-REQUEST-SOUND: "NOTE_PLING"
  
  # Does profile/party duel affect stats?
  DUEL-CHANGES-STATS: true
  
  # Do party games affect stats?
  PARTY-CHANGES-STATS: false
  
  # Ignore the spigot's entity hider and use bolt's instead
  FORCE-ENTITY-HIDER: false
  
  # Should we prevent players from seeing each other at lobby like MMC?
  # This is recommended for 100 player+ server otherwise the spigot itself will start bottlenecking.
  FORCE-HIDE-PLAYERS: false
  
  # Should we update holograms only after leaderboards are updated?
  HOLOGRAMS-UPDATE-AFTER-LEADERBOARDS: true
  
  # The profile statistics saving time in minutes
  # Increasing this from 15 minutes could help performance but also result in data loss
  # Whilst decreasing this time interval can help prevent data loss but also affect performance
  STATS-SAVE-INTERVAL: 15
  
  # The leaderboards updating time in minutes
  # Increasing this from 3 minutes could help performance but also result in slow leaderboards
  # Whilst decreasing this time interval can do the opposite
  LEADERBOARD-UPDATE-INTERVAL: 3
  
  # You can put winner commands here for tournament.
  # These commands are ran on every single winner.
  # The placeholders are <winner> and <kit> for winner and kit name respectively.
  TOURNAMENT-WINNER-COMMANDS:
    - "elo add <winner> <kit> 10"
  
  # Here you can put any commands with the '/' included and bolt will block it
  BLOCKED-COMMANDS: []
  
  # Should HCF-TeamFights be enabled.
  TEAM-FIGHT-ENABLED: true
  
  # Icon to use for progress bars.
  PROGRESS-ICON: "▎"
  
  # Amount of icon characters per progress bar.
  PROGRESS-AMOUNT: 10
  
  # Filled color to use for progress bar.
  PROGRESS-FILLED: "&a"
  
  # Remaining color to use for progress bar.
  PROGRESS-REMAINING: "&7"
PROFILE-SETTINGS:
  
  # The default profile setting for sidebars
  SIDEBAR-ENABLED: true
  
  # The default profile setting for player visibility
  SHOW-PLAYERS: true
  
  # The default profile setting for vanilla tab
  VANILLA-TAB: false
  
  # The default profile setting for duel requests
  DUEL-REQUESTS: true
  
  # The default profile setting for duel sounds
  DUEL-SOUNDS: true
  
  # The default profile setting for play again
  PLAY-AGAIN: true
  
  # The default profile setting for party requests
  PARTY-REQUESTS: true
  
  # The default profile setting for tournament message
  TOURNAMENT-MESSAGES: true
  
  # The default profile setting for spectator messages
  SPECTATOR-MESSAGES: true
  
  # The default profile setting for allowing spectators
  ALLOW-SPECTATORS: true
  
  # The default profile setting for play again rematch
  PLAY-AGAIN-REMATCH: false
  
  # The default profile setting for fly mode
  FLY-MODE: false
  
  # The default profile setting for death animation
  DEATH-ANIMATION: true
  
  # The default profile setting for drop items
  DROP-ITEMS: false
  
  # The default profile setting for clear inventory
  CLEAR-INVENTORY: false
QUEUE:
  
  # Should we periodically send queue ticking messages to players in queue?
  TICKING-MESSAGE-ENABLED: true
  
  # This value is added to the ping range every time the ranges are ticked.
  FIRST-ELO-UPDATE: 25
  
  # How much ping will be added and removed when you start queuing for ranked.
  FIRST-PING-UPDATE: 35
  
  # Queues are ticked everyone 0.2s, So 0.2 * 5 = 1 second of delay.
  ELO-UPDATE-DELAY: 5
  
  # Queues are ticked everyone 0.2s, So 0.2 * 5 = 2 second of delay.
  PING-UPDATE-DELAY: 5
MATCH:
  
  # Here you can put any commands with the '/' included and bolt will block it
  BLOCKED-COMMANDS: []
  
  # The amount of time (in seconds) before the play-again expires.
  PLAY-AGAIN-EXPIRE-SECONDS: 40
  
  # The commands prefixed by 'CONSOLE:' are ran by console when player wins the match and for player, it's 'PLAYER:'
  # Do not put '/' in here, it's automatically done.
  # Example: 'CONSOLE:elo add <winner> NoDebuff 10
  WIN-COMMANDS: []
  
  # The commands prefixed by 'CONSOLE:' are ran by console when player loses the match and for player, it's 'PLAYER:'
  # Do not put '/' in here, it's automatically done.
  # Example: 'CONSOLE:elo remove <loser> NoDebuff 10
  LOSE-COMMANDS: []
  
  # Here you can change the match started sound, the default is NOTE_BASS
  STARTED-SOUND: "NOTE_BASS"
  
  # Here you can change the match countdown sound, the default is NOTE_PLING
  COUNTDOWN-SOUND: "NOTE_PLING"
  
  # Enable the Match Started Title
  # Title and Subtitle is configurable in locale.yml
  SHOW-STARTED-TITLE: true
  
  # Enable the Match Countdown Title
  # Title and Subtitle is configurable in lang.yml
  SHOW-COUNTDOWN-TITLE: true
  
  # Enable the Match Winner Title
  # Title and Subtitle is configurable in lang.yml
  SHOW-WINNER-TITLE: true
  
  # Enable the Match Looser Title
  # Title and Subtitle is configurable in lang.yml
  SHOW-LOOSER-TITLE: true
  
  # Enable the Match Respawn Title
  # Title and Subtitle is configurable in lang.yml
  SHOW-RESPAWN-TITLE: true
  
  # Enable the Match Respawn Countdown Title
  # Title and Subtitle is configurable in lang.yml
  SHOW-RESPAWN-COUNTDOWN-TITLE: true
  
  # Enable the Match Bed Destroyed Title
  # Title and Subtitle is configurable in lang.yml
  SHOW-BED-DESTROYED-TITLE: true
  
  # Remove the bottles from player's hands as soon his drink is empty
  REMOVE-BOTTLES: true
  
  # Should we clear placed blocks after each round of Bridges?
  CLEAR-BLOCKS: false
  
  # Should we allow explosion to damage players?
  EXPLOSION-DAMAGES-PLAYERS: false
  
  # Should crystals be able to break map blocks?
  CRYSTALS-BREAK-MAP-BLOCKS: false
  
  # Should we allow spleef to break a max of 4 in its trajectory?
  SPLEEF-TRAJECTORY: true
  
  # Should we display kill effects in respawn matches like Bridges?
  SHOW-KILL-EFFECTS: false
  
  # Should we send per kit disclaimer message?
  DISCLAIMER-ENABLED: true
  
  # If enabled, players can do /leave in a match to leave the match.
  # This only works for unranked solo matches, any other will say invalid state.
  ALLOW-LEAVE: true
  
  # The minimum amount of won matches required by a player to join Ranked Queue
  # Set this to 0, if you don't want any limit
  RANKED-LIMIT: 10
  
  # The maximum amount of ping a player can have while joining Ranked Queue
  # Set this to 0, if you don't want any limit
  RANKED-MAX-PING: 300
  
  # The amount of time (in seconds) before the duel invite expires.
  DUEL-EXPIRE-SECONDS: 60
  
  # The amount of delay (in seconds) before you get teleported back to spawn
  TELEPORT-DELAY: 4
  
  # The amount of spawn protection (in seconds) when you respawn in BedFight
  SPAWN-PROTECTION: 3
  
  # This enables a timer on all standard matches, after the timer is up, the match is ended in a tie.
  TIME-LIMIT-ENABLED: true
  
  # Specify the time limit in minutes for matches
  TIME-LIMIT-VALUE: 20
  
  # Horizontal multiplier for TNT Sumo
  TNT-SUMO-H: 0.7
  
  # Vertical multiplier for TNT Sumo
  TNT-SUMO-V: 0.6
  
  # Explosion radius for TNT Sumo
  TNT-SUMO-RADIUS: 9.0
  
  # Horizontal value for Fireball
  FIREBALL-H: 1.5
  
  # Vertical value for Fireball
  FIREBALL-V: 1.0
  
  # Horizontal value for TNT
  TNT-H: 1.25
  
  # Vertical value for TNT
  TNT-V: 0.75
  
  # Material for OITQ launch item
  OITQ-ITEM: "IRON_AXE"
  
  # Preferred slot to replace the arrow for OITQ, -1 to add to inventory 
  OITQ-SLOT: 8
  
  # OITQ Horizontal Distance
  OITQ-H: 1.2
  
  # OITQ Vertical Distance
  OITQ-V: 0.65
EVENT:
  
  # Here you can put any commands with the '/' included and bolt will block it
  BLOCKED-COMMANDS: []
  
  # The commands prefixed by 'CONSOLE:' are ran by console when player wins the event and for player, it's 'PLAYER:'
  # Do not put '/' in here, it's automatically done.
  # The prefix must be followed by the event type.
  # Example: 'CONSOLE:SUMO:elo add <winner> NoDebuff 10
  WIN-COMMANDS: []
  
  # Here you can change the match started sound, the default is NOTE_BASS
  STARTED-SOUND: "NOTE_BASS"
  
  # Here you can change the match countdown sound, the default is NOTE_PLING
  COUNTDOWN-SOUND: "NOTE_PLING"
  
  # Cooldown in minutes
  HOST-COOLDOWN: 20


# Configure PlaceholderAPI hook settings here
PLACEHOLDER-API:
  
  # Toggle Match PlaceholderAPI expansion
  MATCH-EXPANSIONS: true
  
  # Toggle Stats PlaceholderAPI expansion
  STATS-EXPANSIONS: true
  
  # Here you can change the format of the leadeboards placeholder
  LEADERBOARD-FORMAT: "&c#<pos> &f<name> &7- &c<value> &7- <division>"


# Configure whether there should be a cool-down for pearls and bows, and what should it be in seconds
TIMER:
  PEARL:
    ENABLED: true
    VALUE: 15.0
  BRIDGE-BOW:
    ENABLED: true
    VALUE: 5.0
  FIRE-BALL:
    ENABLED: true
    VALUE: 2.0
  TNT-SUMO:
    ENABLED: true
    VALUE: 0.5
  INSTANT-GOLDEN-HEAD:
    ENABLED: true
    VALUE: 2.0


# Here you can configure the format of the Holograms
HOLOGRAMS:
  DEFAULT-LINES:
    - "&c&lGlobal Leaderboards"
    - "&7"
    - "&e◉ <type> &e◉"
    - "&7"
    - "<c>&c#1 &f<player1> &7- &c<value1> &7- <division1>"
    - "<c>&c#2 &f<player2> &7- &c<value2> &7- <division2>"
    - "<c>&c#3 &f<player3> &7- &c<value3> &7- <division3>"
    - "<c>&c#4 &f<player4> &7- &c<value4> &7- <division4>"
    - "<c>&c#5 &f<player5> &7- &c<value5> &7- <division5>"
    - "<c>&c#6 &f<player6> &7- &c<value6> &7- <division6>"
    - "<c>&c#7 &f<player7> &7- &c<value7> &7- <division7>"
    - "<c>&c#8 &f<player8> &7- &c<value8> &7- <division8>"
    - "<c>&c#9 &f<player9> &7- &c<value9> &7- <division9>"
    - "<c>&c#10 &f<player10> &7- &c<value10> &7- <division10>"
    - "&7"
    - "&fNext update in &c<update>"
  KIT-LINES:
    - "&c&l<type> Leaderboards"
    - "&7"
    - "&e◉ <kit> &e◉"
    - "&7"
    - "<c>&c#1 &f<player1> &7- &c<value1> &7- <division1>"
    - "<c>&c#2 &f<player2> &7- &c<value2> &7- <division2>"
    - "<c>&c#3 &f<player3> &7- &c<value3> &7- <division3>"
    - "<c>&c#4 &f<player4> &7- &c<value4> &7- <division4>"
    - "<c>&c#5 &f<player5> &7- &c<value5> &7- <division5>"
    - "<c>&c#6 &f<player6> &7- &c<value6> &7- <division6>"
    - "<c>&c#7 &f<player7> &7- &c<value7> &7- <division7>"
    - "<c>&c#8 &f<player8> &7- &c<value8> &7- <division8>"
    - "<c>&c#9 &f<player9> &7- &c<value9> &7- <division9>"
    - "<c>&c#10 &f<player10> &7- &c<value10> &7- <division10>"
    - "&7"
    - "&fNext update in &c<update>"
COIN-SYSTEM:
  
  # Toggle whether you want to enable bolt's coin system?
  # This won't disable the shop system, that can be disabled in shop.yml.
  ENABLED: true
  
  # The provider for coins are Bolt, Vault.
  PROVIDER: "Bolt"
  
  # The amount of coins given to a player on a daily basis.
  DAILY-COINS: 100
  
  # Should duels give coin rewards?
  DUEL-GIVES-COINS: true
  
  # Should party events give coin rewards?
  PARTY-GIVES-COINS: false
  
  # The amount of coins given on kill.
  KILL-REWARD: 1
  
  # The amount of coins given on winning a match.
  WIN-REWARD: 5
  
  # The amount of coins given on scoring a point in match.
  SCORE-REWARD: 1
  
  # The amount of coins given on destroying a bed in match.
  BED-DESTROY-REWARD: 2
  
  # The amount of coins given on having a perfect (100) combo in boxing.
  PERFECT-BOXING-REWARD: 15
NAME-TAGS:
  
  # Toggle whether Bolt's NameTag system should be enabled or not
  ENABLED: true
  
  # You can change lobby name-tag here
  LOBBY-PREFIX: "&a"
  LOBBY-SUFFIX: ""
  
  # You can change party name-tag prefix here
  PARTY-PREFIX: "&9"
  PARTY-SUFFIX: ""
  
  # You can change queue name-tag prefix here
  QUEUE-PREFIX: "&e"
  QUEUE-SUFFIX: ""
  
  # You can change event name-tag prefix here
  EVENT-PREFIX: "&b"
  EVENT-SUFFIX: ""
  
  # You can change blue team name-tag prefix here
  BLUE-TEAM-PREFIX: "&9[B] &9"
  
  # You can change red team name-tag prefix here
  RED-TEAM-PREFIX: "&c[R] &c"
  
  # You can change vanish name-tag prefix here
  VANISH-PREFIX: "&a"
  VANISH-SUFFIX: "&r &7[V]"


# Should we log stats saving in console?
LOGGING:
  STATS-LOGS: false
